version: 2.1

orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-parameter-store: circleci/aws-parameter-store@1.0.0
  aws-ecr: circleci/aws-ecr@3.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  publish-package:
    parameters:
      aws-account:
        type: string
    steps:
      - run: 
          command: |
            SET NUGET_FEED_URL=${aws-parameter-store/nuget/<<parameters.environment>>/NUGET_FEED_URL} 
            SET NUGET_KEY=${aws-parameter-store/nuget/<<parameters.environment>>/NUGET_KEY}

jobs:
  dotnet-pack: 
    executor: docker-dotnet
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            dir
            cd ./Hackney.Core
            dotnet pack --configuration Release
  publish-package:
    executor: docker-dotnet
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Publish to NuGet
          command: |
            dotnet nuget push "${NUGET_FEED_URL}" --api-key "${NUGET_KEY}" --source "https://nuget.pkg.github.com/LBHackney-IT/"

workflows:
  nuget-package:
    jobs:
      - dotnet-pack
      - publish-package:
          requires:   
            - dotnet-pack