version: 2.1

orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-ecr: circleci/aws-ecr@3.0.0

executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root     

# commands:
  
#   publish-package:
#     description: "Publishes the Package to GitHub"
#     steps:
#       - *attach_workspace
#       - checkout    
#       - run: 
#           name: Get values from Parameter store
#           command: |
#             dotnet nuget push --source $NUGET_FEED_URL --api-key $NUGET_KEY */.nupkg 

jobs:
  dotnet-pack:
    executor: docker-dotnet
    steps:      
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            dir
            cd ./Hackney.Core
            dotnet pack --configuration Release
  publish-package:
    executor: docker-dotnet
    steps:
      - *attach_workspace
      - checkout    
      - run: 
          name: Publish to GitHub
          command: |
            dotnet nuget push --source $NUGET_FEED_URL --api-key $NUGET_KEY

workflows:
  nuget-package:
    jobs:
      - dotnet-pack
      - publish-package:
          requires:   
            - dotnet-pack
