version: 2.1
orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-ecr: circleci/aws-ecr@3.0.0
executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root     
jobs:
  publish-package:
    executor: docker-dotnet
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            cd ./Hackney.Core
            dotnet pack --configuration Release
      - run: 
          name: Publish to GitHub
          command: |
            cd /root/project/Hackney.Core/bin/Release
            dotnet nuget push Hackney.Core.*.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${NUGET_KEY} Hackney.Core.*/*.nupkg

workflows:
  nuget-package:
    jobs:
      - publish-package:
          filters:
            branches:
              only: release
    
          


