version: 2.1
orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-ecr: circleci/aws-ecr@3.0.0
executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root     
jobs:
  dotnet-pack:
    executor: docker-dotnet
    steps:      
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            dir
            cd ./Hackney.Core
            dotnet pack --configuration Release
      # - persist_to_workspace:
      #     root: Hackney.Core/
      #     paths:
      #       - Hackney.Core.1.0.0.nupkg
  publish-package:
    executor: docker-dotnet
    steps:
      # - *attach_workspace
      - checkout    
      - run: 
          name: Publish to GitHub
          command: |
            dotnet nuget push --source /Hackney.Core.1.0.0.nupkg --api-key ${NUGET_KEY} Hackney.Core/Hackney.Core.1.0.0/*.nupkg
workflows:
  nuget-package:
    jobs:
      - dotnet-pack
      - publish-package:
          requires:   
            - dotnet-pack