version: 2.1
orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-ecr: circleci/aws-ecr@3.0.0
executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root     

jobs:
  dotnet-pack:
    executor: docker-dotnet
    steps:      
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            dir
            cd ./Hackney.Core
            dotnet pack --configuration Release
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - project/Hackney.Core/
  publish-package:
    executor: docker-dotnet
    steps:
      - *attach_workspace
      - run:
          name: Set Version Variable
          command: echo "VERSION"
      - run: 
          name: Publish to GitHub
          command: |
            cd ./Hackney.Core/
            dir
            dotnet nuget push Hackney.Core.1.0.0.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${NUGET_KEY} Hackney.Core.1.0.0/*.nupkg
# /tags\/v/
  version-package:
    executor: docker-dotnet
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            dir
            cd ./Hackney.Core
            dotnet pack --configuration Release /p:NuGetVersion= ${CIRCLE_TAG}
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - project/Hackney.Core/
            - NuGetVersion
      - run: 
          name: Publish to GitHub
          command: |
            cd ./Hackney.Core/
            dir
            dotnet nuget push Hackney.Core.NuGetVersion.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${NUGET_KEY} Hackney.Core.1.0.0/*.nupkg

workflows:
  nuget-package:
    jobs:
      # - dotnet-pack
      # - publish-package:
      #     requires:   
      #       - dotnet-pack
      #     filters:
      #       branches:
      #         only: release
      - version-package:
          filters:
            tags:
              only: "v[0-9]+.[0-9]+.[0-9]+"
    
          


