version: 2.1

orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-ecr: circleci/aws-ecr@3.0.0

executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root     

commands:
  publish-package:
    description: "Publishes the Package to GitHub"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout    
      - run:
          name: Install AWS CLI
          command: |
            curl -L -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
            unzip awscliv2.zip
            ./aws/install  
      - run: 
          name: Get values from Parameter store
          commmand: |
           NUGET_FEED_URL=$(aws ssm get-parameter --name /nuget/<<parameters.stage>>/NUGET_FEED_URL --query Parameter.Value)
           NUGET_KEY=$(aws ssm get-parameter --name /nuget/<<parameters.stage>>/NUGET_KEY --query Parameter.Value)
           dotnet nuget push --source ${NUGET_FEED_URL} --api-key ${NUGET_KEY} */.nupkg 

jobs:
  dotnet-pack:
    executor: docker-dotnet
    steps:      
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            dir
            cd ./Hackney.Core
            dotnet pack --configuration Release
  publish-package-development:
    executor: docker-dotnet
    steps:
      - checkout      
      - *attach_workspace
      - publish-package:
          stage: "development"
  publish-package-staging:
    executor: docker-dotnet
    steps:
      - checkout      
      - *attach_workspace
      - publish-package:
          stage: "staging"
  publish-package-production:
    executor: docker-dotnet
    steps:
      - checkout      
      - *attach_workspace
      - publish-package:
          stage: "production"

workflows:
  nuget-package-development:
    jobs:
      - dotnet-pack
      - publish-package-development:
          requires:   
            - dotnet-pack
