version: 2.1

orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-parameter-store: circleci/aws-parameter-store@1.0.0
  aws-ecr: circleci/aws-ecr@3.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

commands:
  publish-package:
    parameters:
      aws-account:
        type: string
    steps:
      - run: 
          command: |
          NUGET_FEED_URL="${aws-parameter-store/<<parameters.environment>>/NUGET_FEED_URL}" 
          NUGET_KEY="${{aws-parameter-store/<<parameters.environment>>/NUGET_KEY}" 

jobs:
  publish-package: 
    executor: docker-dotnet
    steps:
      - run:
          name: Push to NuGet
          command: |
            dotnet pack --output Hackney.Core --configuration Release
            dotnet nuget push --source NUGET_FEED_URL --api-key NUGET_KEY Hackney.Core/*.nupkg

workflows:
  publish-package:
    jobs:
      - publish-package
          

