name: Hackney.Core.JWT-publish
on:
  push:
    branches:
    - release
    - feature/**
    paths:
      - "src/Hackney.Core.JWT/**"
      - "tests/Hackney.Core.Tests.JWT/**"
      - ".github/workflows/Hackney.Core.JWT.yml"
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine package version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Display package version
        run: |
          echo "Version: $GITVERSION_NUGETVERSIONV2"
          
  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet format
        run: |
          cd src
          dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - name: Run formatter check
        run: |
          cd src
          ./dotnet-format-local/dotnet-format --check Hackney.Core.JWT

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    outputs:
      version: ${{ needs.calculate-version.outputs.version }}
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose build hackney-core-jwt-test
      - name: Run tests
        run: docker-compose run hackney-core-jwt-test

  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      VERSION: ${{ needs.build-and-test.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Package
        run: |
          cd src
          dotnet pack Hackney.Core.JWT -p:PackageVersion=$VERSION --configuration Release
      - name: Publish the Package
        run: |
          cd src/Hackney.Core.JWT/bin/Release
          dotnet nuget push Hackney.Core.JWT.*.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${{secrets.NUGET_KEY }}