name: Hackney.Core.Testing-publish
on:
  push:
    branches:
    - release
    - feature/**
    paths:
      - "Hackney.Core/Hackney.Core.Testing/**"
      # - "Hackney.Core.Tests/Hackney.Core.Tests.Hackney.Core.Testing/**"
      - ".github/workflows/Hackney.Core.Testing.yml"
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine package version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Display package version
        run: |
          echo "Version: $GITVERSION_NUGETVERSIONV2"

  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet format
        run: |
          cd Hackney.Core
          dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - name: Run formatter check
        run: |
          cd Hackney.Core
          ./dotnet-format-local/dotnet-format --check Hackney.Core.Testing

  # build-and-test:
  #   name: Build & Test
  #   runs-on: ubuntu-latest
  #   needs: calculate-version
  #   env:
  #     LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
  #   outputs:
  #     version: ${{ needs.calculate-version.outputs.version }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: docker-compose build hackney-core-testing-test
  #     - name: Run tests
  #       run: docker-compose run hackney-core-testing-test

  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      VERSION: ${{ needs.calculate-version.outputs.version }}
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Package
        run: |
          cd Hackney.Core
          dotnet pack Hackney.Core.Testing -p:PackageVersion=$VERSION --configuration Release
      - name: Publish the Package
        run: |
          cd Hackney.Core/Hackney.Core.Testing/bin/Release
          dotnet nuget push Hackney.Core.Testing.*.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${{secrets.NUGET_KEY }}